/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virna5.graph;

import com.mxgraph.swing.mxGraphOutline;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.Mode;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.virna5.graph//GraphOutline//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GraphOutlineTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "com.virna5.graph.GraphOutlineTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GraphOutlineAction",
        preferredID = "GraphOutlineTopComponent"
)
@Messages({
    "CTL_GraphOutlineAction=GraphOutline",
    "CTL_GraphOutlineTopComponent=Navegador",
    "HINT_GraphOutlineTopComponent=Navegador do Designer de Tarefas"
})
public final class GraphOutlineTopComponent extends TopComponent {

    private static final Logger log = Logger.getLogger(GraphOutlineTopComponent.class.getName());

    private static final String PREFERRED_ID = "GraphOutlineTopComponent";
    private static GraphOutlineTopComponent instance;
    
    public static synchronized GraphOutlineTopComponent getDefault() {
        if (instance == null) {
            instance = new GraphOutlineTopComponent();
        }
        return instance;
    }
    
    /**
     * Obtain the TopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized GraphOutlineTopComponent findInstance() {
        
        Mode propmode = WindowManager.getDefault().findMode("properties");
        //TopComponent win = GraphOutlineTopComponent.getRegistry().getActivated();
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            log.log(Level.INFO, "Não foi possivel encontrar o componente " + PREFERRED_ID);
            getDefault();
            propmode.dockInto(instance);
            instance.open();
            instance.requestActive();
            return instance;
        }
        if (win instanceof GraphOutlineTopComponent) {
            log.log(Level.INFO, "Component " + PREFERRED_ID+ " is already active");
            propmode.dockInto(win);
            win.open();
            win.requestActive();
            return (GraphOutlineTopComponent) win;
        }
        log.log(Level.WARNING, 
                "Parece que há várias instancias do ID '" + PREFERRED_ID
                + "' Isso é uma fonte potencial de problemas e comportamento errático");
        return getDefault();
    }

    
    public GraphOutlineTopComponent() {
        initComponents();
        setName(Bundle.CTL_GraphOutlineTopComponent());
        setToolTipText(Bundle.HINT_GraphOutlineTopComponent());
    }

    public void addOutlinePane(mxGraphOutline pane){
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
